---
fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    chocolatey: https://github.com/puppetlabs/puppetlabs-chocolatey.git
    facts: https://github.com/puppetlabs/puppetlabs-facts.git
    provision: https://github.com/puppetlabs/provision.git
    puppet_agent: https://github.com/puppetlabs/puppetlabs-puppet_agent.git
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "v9.7.0"
    yumrepo_core:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core"
      ref: "0a1b7a2a2d7fbf2eb53db4aed04ac55f15a2fba5"
  symlinks:
    osquery: "#{source_dir}"
