---
appveyor.yml:
  delete: true
.gitignore:
  paths:
    - /[Bb]ackup*/
    - /.devcontainer/
    - /.gitlab-ci.yml
    - /.travis.yml
    - /.vscode/
    - /appveyor.yml
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true
.devcontainer:
  delete: true
.vscode:
  delete: true
.pdkignore:
  paths:
    - /[Bb]ackup*/
    - /provision.yaml
Gemfile:
  unmanaged: false
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '~> 1.15'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"
      - gem: 'puppet-lint-file_ensure-check'
        require: false
      - gem: 'puppet-lint-manifest_whitespace-check'
        require: false
      - gem: 'puppet-lint-trailing_comma-check'
        require: false
      - gem: 'puppet-lint-optional_default-check'
        require: false
    ':test':
      - gem: 'puppet_metadata'
        version: '~> 1.0'
spec/spec_helper.rb:
  coverage_report: true
  spec_overrides:
    - 'RSpec.configure do |c|'
    - '  c.facter_implementation = :rspec'
    - 'end'
.puppet-lint.rc:
  enabled_lint_checks:
    - 140chars
    - 2sp_soft_tabs
    - arrow_alignment
    - class_inherits_from_params_class
    - double_quoted_strings
    - duplicate_params
    - file_ensure
    - file_mode
    - hard_tabs
    - leading_zero
    - manifest_whitespace_opening_brace_after
    - nested_classes_or_defines
    - only_variable_string
    - optional_default
    - parameter_documentation
    - parameter_order
    - parameter_types
    - quoted_booleans
    - right_to_left_relationship
    - slash_comments
    - star_comments
    # - strict_indent
    - trailing_comma
    - trailing_whitespace
    - unquoted_file_mode
    - variable_contains_dash
    - variable_is_lowercase
    - variable_scope
    - variables_not_enclosed
